version: '3.8'
services:
  database:
    container_name: pg-foodcourt
    # image: postgres:15
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql'
    restart: always
  pgadmin:
    container_name: pgadmin-foodcourt
    image: dpage/pgadmin4:6.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  pg_data:
